DEVICE: 'cuda' 
MODEL:
  BODY: "FFCR"

  FFCR:
    BODY: 50
    OUT_DIM: 64 
    USE_SE: False

LOADER: 
  DATASET: "WBLOT"
  GPU_BATCH_SIZE: 128
  # BATCH_SIZE:  null
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5
  SIZE: 38200

  LEAVE_OUT: null # could be 0..5

SOLVER:
  MAX_ITER: 5000
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  CHECKPOINT_PERIOD: 100

  OPTIM: 
    BODY: "LAMB"
    BASE_LR: 0.04
    DECAY: 0.0005
    MOMENTUM: 0.9 
    BETAS: [0.9, 0.99]

LOSS: 
  BODY: "ARC" 

  ARC:
    SCALE: 64

EXP:
  TRAIN: True
  TEST: True
  PLOTS:
  - "EMBED"
  - "PCA"
  - "CONFUSION"
  - "DPRIME"
  - "TSNE"
