MODEL:
  BODY: "FFCR"

  FFCR:
    BODY: 50
    OUT_DIM: 64 # 5 classes but its  embed dim
    USE_SE: False

LOADER: 
  DATASET: "WBLOT"
  GPU_BATCH_SIZE:  128 
  LEAVE_N_OUT: 1
  # BATCH_SIZE:  null 
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5
  SIZE: 38200
  
SOLVER:
  MAX_ITER: 5000 
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  CHECKPOINT_PERIOD: 100

  OPTIM: 
    BODY: "LAMB"
    BASE_LR: 0.04
    DECAY: 0.0005 # 5e-4
    MOMENTUM: 0.9
    BETAS: [0.9, 0.99]


LOSS: 
  BODY: "ARC" 

  ARC:
      L6_SCALE: 50

EXP:
  BODY: "5x2"
  PARTITION: TRUE
  TRAIN: True
  TEST: True
  PLOTS:
  - "EMBED"
  - "PCA"
  - "DPRIME"
  - "CONFUSION"
  - "RKNN"
  - "TSNE"
