DEVICE: 'cuda' # TODO add implicit GPU detection

MODEL:
  BODY: "RESNET_FROM_SCRATCH"
  ODIM: 5

LOADER: 
  DATASET: "WBLOT"
  BATCH_SIZE: 128
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5 
  SIZE: 38200

  LEAVE_OUT: null

SOLVER:
  MAX_EPOCH: 20
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  SEED: 0 # default ... why in solver

  OPTIM: 
    BODY: "LAMB"
    BASE_LR: 0.04
    DECAY: 0.0005
    MOMENTUM: 0.9 
    BETAS: [0.9, 0.99]


LOSS: 
  BODY: "CE" 

EXP:
  TRAIN: True
  TEST: True
  PLOTS:
  - "CONFUSION"
