
loc: /grand/EVITA/datasets
train: []
test: []
use_crowd: false
class_agnostic: false
class_concat: false
max_box: -1
sample_ratio: 0.0
few_shot: 0
shuffle_seed: 0
predefined_text: ""
alternative_training: false
multistage_training: false
register: {}
box_threshold: 0.1
coco_copy: 1
lvis_copy: 1
flickr_copy: 1
mixed_copy: 1
object365_copy: 1
vg_copy: 1
oi_copy: 1
in_copy: 1
general_copy: -1
general_copy_test: -1
random_sample_neg: -1
add_det_prompt: false
add_det_prompt_advanced: false
use_od_aug: false
use_coco_format: false
control_prob: []
disable_shuffle: false
prompt_version: ""
prompt_limit_neg: -1
pos_question_prob: 0.6
neg_question_prob: 0.8
full_question_prob: 0.5
one_hot: false
no_minus_one_for_one_hot: false
disable_clip_to_image: false
separation_tokens: " "
lvis_use_normal_ap: false
special_safeguard_for_coco_grounding: false
bing_index_list: []
caption_min_box: 1
replace_clean_label: false
further_screen: false
caption_conf: 0.9
caption_nms: 0.9
pack_random_caption_number: 0
inference_caption: false
sample_negative_for_grounding_data: -1.0
random_pack_prob: -1.0
no_random_pack_probability: 0.0
safeguard_positive_caption: true
caption_format_version: "v1"
local_debug: false
train_datasetname_suffix: ""
test_datasetname_suffix: ""
override_category: null
use_override_category: false
supress_query: null
use_supress_query: false
use_caption_prompt: false
caption_prompt: null
flickr_gt_type: "separate"
diver_box_for_vqa: false
