DEVICE: 'cuda' 
AMP: True
MODEL: 
  BODY: "IRESNET"

  IRESNET:
    BODY: "IR18" # "IR50"
    OUT_DIM: 64

  RESNET: "ResNet50Conv5ROIFeatureExtractor"

  VIT: 
    SIZE: 'B' # B,  L, H

    IMAGE_SIZE: 256
    PATCH: 16
    NCLASSES: 5
    FE: True # is feature extractor

    # DIM:
    # LAYERS:
    # HEADS:
    # MLP_DIM:

    # DROPOUT:
    # EMB_DROPOUT:
    # POOL:
    # CHANNELS: 
    # DIM_HEAD: 

  SWINT:
    EMBED_DIM: 96
    DEPTHS: (2, 2, 6, 2)
    NUM_HEADS: (3, 6, 12, 24)
    WINDOW_SIZE: 7
    MLP_RATIO: 4
    DROP_PATH_RATE:  0.2
    APE: False # absolute positional embedding

  # VISION:
    # FREEZE_CONV_BODY_AT: 
    # CONV_BODY: 
    # USE_CHECKPOINT: 
    # OUT_FEATURES: 

  FFCR:
    BODY: '50'
    # LAYERS: [3,4,6,3]
    OUT_DIM: 5
    USE_SE: False

LOADER:
  X: True
  DATASET: "WBLOT"
  BATCH_SIZE: 64 # 512 # try bigger batch size !!!
  SHUFFLE: True
  TRAIN: True
  VAL: True
  NCLASSES: 5

SOLVER:
  MAX_EPOCH: 50
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  SEED: 0 # default ... why is it in solver?

LOSS:
  BODY:  "AAM" # additive angular margin

  AAM:
    S: 64.0
    M: [1.0, 0.0, 0.4]
    INTER_THRESH: 0

  PFC:
    EMBED_DIM: 64   # 3
    NC: 5
    NCLASSES: 5
    SAMPLE_RATE:  0.2 # original is 0.2 ... 1

OPTIM:
  BODY: "ADAM"

  LR: 0.001 # 0.005 # 0.1
  BETAS: [0.5,0.999]
  DECAY: 5e-4

TRAINER:
  TRAIN: True
  VAL: True
