DEVICE: 'cuda' # TODO add implicit GPU detection

MODEL:
  BODY: "CUSTOM"

  CUSTOM:
    KEY: "ffc_arc64"
    ODIM: 5

  FFCR:
    BODY: 50
    LAYERS: [3,4,6,3]
    OUT_DIM: 64 # 5 classes but its  embed dim
    USE_SE: False

LOADER: 
  DATASET: "WBLOT"
  BATCH_SIZE: 128 # is possible
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5
  SIZE: 38200
  
  LEAVE_OUT: null # could be 0..5

SOLVER:
  MAX_EPOCH: 20 # you said 200 but 20 is on arcface
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0

LOSS: 
  BODY: "CE" 

OPTIM: 
  BODY: "SGD" # "ADAM"
  LR: 0.001 # extra low since its already trained a bit
  DECAY: 5e-4
  MOMENTUM: 0.9

SCHEDULER:
  BODY: "STEP"

EXP:
  TRAIN: True
  TEST: True
  PLOTS:
  - "CONFUSION"
