DEVICE: 'cuda' # TODO add implicit GPU detection

MODEL:
  BODY: "SRNET"
  ODIM: 64

  FFCR:
    BODY: 50
    OUT_DIM: 64 # 5 classes but its  embed dim
    USE_SE: False

LOADER: 
  DATASET: "WBLOT"
  GPU_BATCH_SIZE:  128 
  LEAVE_N_OUT: 1
  # BATCH_SIZE:  null 
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5
  SIZE: 38200
  
  LEAVE_OUT: null # could be 0..5

SOLVER:
  MAX_ITER: 3000 
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  CHECKPOINT_PERIOD: 100

  OPTIM: 
    BODY: "LAMB"
    BASE_LR: 0.04
    DECAY: 0.0005 # 5e-4
    MOMENTUM: 0.9
    BETAS: [0.9, 0.99]


LOSS: 
  BODY: "ARC" 

  AAM:
    S: 64.0
    M: [1.0, 0.5, 0.0]
    INTER_THRESH: 0

  PFC: 
    EMBED_DIM: 64
    NCLASSES: 5
    SAMPLE_RATE:  1.0

EXP:
  BODY: "5x2"
  REVERSE: False
  TRAIN: True
  TEST: True
  PLOTS:
  - "CENTER"
  - "EMBED"
  - "CONFUSION"
  - "RKNN"
  - "TSNE"
  - "PCA"
  - "DPRIME"
