DEVICE: 'cuda' # TODO add implicit GPU detection

MODEL:
  BODY: "FFCR"

  FFCR:
    BODY: 50
    OUT_DIM: 64 # 5 classes but its  embed dim
    USE_SE: False

LOADER: 
  DATASET: "WBLOT"
  GPU_BATCH_SIZE:  128 
  # BATCH_SIZE:  null 
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5
  SIZE: 38200
  
  LEAVE_OUT: null # could be 0..5

SOLVER:
  MAX_EPOCH: 20 # you said 200 but 20 is on arcface
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  CHECKPOINT_PERIOD: 100

LOSS: 
  BODY: "AAM" # aam uses pfc sampler

  AAM:
    S: 64.0
    M: [1.0, 0.0, 0.4]
    INTER_THRESH: 0

  PFC: 
    EMBED_DIM: 64
    NC: 5
    NCLASSES: 5
    SAMPLE_RATE:  1.0

OPTIM: 
  BODY: "ADAM"
  LR: 0.04 
  DECAY: 5e-4
  MOMENTUM: 0.9
  BETAS: [0.9, 0.99]

EXP:
  TRAIN: False # True
  TEST: True
  PLOTS:
  - "CONFUSION"
  - "RKNN"
  - "TSNE"
  - "PCA"
  - "DPRIME"
