DEVICE: 'cuda' # TODO add implicit GPU detection

MODEL:
  BODY: "RESNET_FROM_SCRATCH"
  ODIM: 5

LOADER: 
  DATASET: "WBLOT"
  BATCH_SIZE: 128
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5
  SIZE: 38200

  LEAVE_OUT: null

SOLVER:
  MAX_EPOCH: 30
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  SEED: 0 # default ... why in solver

LOSS: 
  BODY: "CE" 

OPTIM: 
  BODY: "ADAM"
  LR: 0.01
  BETAS: [0.5, 0.999]
  DECAY: 5e-4

SCHEDULER:
  BODY: "STEP"

EXP:
  TRAIN: True
  TEST: True
  PLOTS:
  - "CONFUSION"

