DEVICE: 'cuda' # TODO add implicit GPU detection

MODEL:
  BODY: "SRNET"
  ODIM: 5

LOADER: 
  DATASET: "WBLOT"
  BATCH_SIZE: 128 # is possible
  SHUFFLE: True
  SPLIT: True
  NCLASSES: 5
  SIZE: 38200
  
  LEAVE_OUT: null # could be 0..5

SOLVER:
  MAX_EPOCH: 30 # you said 200 but 20 is on arcface
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0

LOSS: 
  BODY: "CE" 

SCHEDULER:
  BODY: "STEP"

OPTIM: 
  BODY: "SGD" # "ADAM"
  LR: 0.01
  DECAY: 5e-4
  MOMENTUM: 0.9

EXP:
  TRAIN: True
  TEST: True
  PLOTS:
  - "CONFUSION"
