DEVICE: 'cuda' # TODO add implicit GPU detection
MODEL:
  BODY: "FFCR"

  FFCR:
    BODY: '50'
    LAYERS: [3,4,6,3]
    NUM_CLASSES: 2 # 5 but its  embed dim
    USE_SE: False

LOADER: 
  DATASET: "WBLOT"
  BATCH_SIZE: 128
  SHUFFLE: True
  USE_SPLIT: True
  SPLIT: [0,1]
  NCLASSES: 5

SOLVER:
  MAX_EPOCH: 80
  GRAD_CLIP: 5.0
  CHECKPOINT_PER_EPOCH: 1.0
  SEED: 0 # default ... why in solver

LOSS: 
  BODY: "AAM" # aam uses pfc sampler

  AAM:
    S: 64.0
    M: [1.0, 0.0, 0.4]
    INTER_THRESH: 0

  PFC: 
    EMBED_DIM: 2
    NC: 5
    NCLASSES: 5
    SAMPLE_RATE: 1.0
    FP16: False

OPTIM: 
  BODY: "ADAM"
  LR: 0.01
  BETAS: [0.5, 0.999]
  DECAY: 5e-4

TRAINER:
  TRAIN: False
  VAL: True
