
use_ra: 0
flip_prob_train: 0.5
vertical_flip_prob_train: 0.0
mult_min_size_train: []
brightness: 0.0
contrast: 0.0
saturation: 0.0
hue: 0.0
crop_prob: 0.5
crop_min_ious: [0.1, 0.3, 0.5, 0.7, 0.9]
crop_min_size: 0.3
