MODEL: 

  # from GLIP defaults
  RPN_ONLY: False
  BOX_ON: True
  MASK_ON: False
  KEYPOINT_ON: False
  DEVICE: "cuda"

  RPN_ARCHITECTURE: "RPN"
  DEBUG: False
  ONNX: False

  # other
  RPN_ARCHITECTURE: "VLDYHEAD"

  VISION:
    BODY: "VIDEO-SWIN"
    DROP_PATH_RATE: 0.4 # IS THAT TOO HIGH??

  LANG:
    BODY: "bert-base-uncased"
    FREEZE: False
    TOKENIZER: "CLIP" 

  DYHEAD: 
    CHANNELS: 256
    NUM_CONVS: 8

    USE_GN: True
    USE_DYRELU: True
    USE_DFCONV: True
    USE_DYFUSE: True

    TOPK: 9 # topk for selecting candidate positive samples from each level
    SCORE_AGG: "MEAN"
    LOG_SCALE: 0.0
    USE_CHECKPOINT: True

    FUSE_CONFIG:
      TYPE: "MHA-B"

      EARLY_FUSE_ON: True
      USE_FUSED_FEATURES_DOT_PRODUCT: True
      USE_CLASSIFICATION_LOSS: False
      USE_TOKEN_LOSS: False
      USE_CONTRASTIVE_ALIGN_LOSS: False
      CONTRASTIVE_HIDDEN_DIM: 64
      USE_DOT_PRODUCT_TOKEN_LOSS: True
      USE_LAYER_SCALE: True

      CLAMP_MIN_FOR_UNDERFLOW: True
      CLAMP_MAX_FOR_OVERFLOW: True
      CLAMP_BERTATTN_MIN_FOR_UNDERFLOW: True
      CLAMP_BERTATTN_MAX_FOR_OVERFLOW: True
      CLAMP_DOT_PRODUCT: True

