site_name: "MALEX: Machine Learning EXperiment"
site_url: null
repo_url: https://github.com/mhyatt000/vision
repo_name: mhyatt000/vision

theme: 
  name: material # readthedocs
  features:
  - content.code.copy
  - navigation.tabs
    # - navigation.sections

  palette:
    primary: teal

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition

nav: 
- Home: index.md
- Installation: install.md
- Usage: usage.md
- MALEX: 
  - Overview: malex/overview.md
  - Config: malex/config.md
  - Model:
    - Catalogue: malex/model/catalogue.md
    - Layers: malex/model/layers.md
  - Data: malex/data.md
  - Helpers: 
    - Experiment: malex/helpers/experiment.md
    - Trainer: malex/helpers/trainer.md
- TODO: todo.md
